import { Project, VariableDeclarationKind } from "ts-morph";
import { GeneratorComments, KwilAction, Value } from "../parser";

function toCamelCase(snake: string): string {
  return snake.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

export function generateTypescript(methods: KwilAction[]) {
  const project = new Project();
  const sourceFile = project.createSourceFile("generated_actions.ts", "", { overwrite: true });

  sourceFile.insertText(0, "// WARNING:");
  sourceFile.insertText(0, "\n");
  sourceFile.insertText(0, "// This file is generated by the generator. Do not edit it manually.");
  sourceFile.insertText(0, "\n");
  sourceFile.insertText(0, "// Any changes you make will be overwritten.");
  sourceFile.insertText(0, "\n");

  sourceFile.addImportDeclarations([
    {
      moduleSpecifier: "@idos-network/kwil-js",
      namedImports: ["Utils"],
    },
    {
      moduleSpecifier: "zod",
      defaultImport: "* as z",
    },
    {
      moduleSpecifier: "../",
      isTypeOnly: true,
      namedImports: ["KwilActionClient"],
    },
  ]);

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "DataType",
        type: "typeof Utils.DataType",
        initializer: `Utils.DataType`,
      }
    ]
  })

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "WALLET_TYPES",
        initializer: `['EVM', 'NEAR', 'XRPL', 'Stellar', 'FaceSign', 'MM'] as const`,
      }
    ]
  })

  sourceFile.addTypeAlias({
    isExported: true,
    name: "WalletType",
    type: "(typeof WALLET_TYPES)[number]",
  });

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "walletTypeSchema",
        type: "z.ZodType<WalletType>",
        initializer: `z.enum(WALLET_TYPES)`,
      }
    ]
  });

  // add_wallet and add_wallet_message reject MM. upsert_wallet_as_inserter keeps walletTypeSchema.
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "ADD_WALLET_TYPES",
        initializer: `['EVM', 'NEAR', 'XRPL', 'Stellar', 'FaceSign'] as const`,
      }
    ]
  })

  sourceFile.addTypeAlias({
    isExported: true,
    name: "AddWalletType",
    type: "(typeof ADD_WALLET_TYPES)[number]",
  });

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "addWalletTypeSchema",
        type: "z.ZodType<AddWalletType>",
        initializer: `z.enum(ADD_WALLET_TYPES)`,
      }
    ]
  });

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "ENCRYPTION_PASSWORD_STORES",
        initializer: `['user', 'mpc', 'mm'] as const`,
      }
    ]
  })

  sourceFile.addTypeAlias({
    isExported: true,
    name: "EncryptionPasswordStore",
    type: "(typeof ENCRYPTION_PASSWORD_STORES)[number]",
  });

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "encryptionPasswordStoreSchema",
        type: "z.ZodType<EncryptionPasswordStore>",
        initializer: `z.enum(ENCRYPTION_PASSWORD_STORES)`,
      }
    ]
  });

  // Blob-backed credential fields: schema CHECK requires content_size > 0 and
  // actions validate content_uri via idos.validate_content_uri (ipfs://…).
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: "IPFS_URI_PREFIX",
        initializer: `"ipfs://"`,
      },
      {
        name: "UKYC_URI_PREFIX",
        initializer: `"ukyc://"`,
      }
    ],
  });

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: "blobContentUriSchema",
        initializer: "z.string().refine( (value) => value.startsWith(IPFS_URI_PREFIX) || value.startsWith(UKYC_URI_PREFIX), `content_uri must start with ${IPFS_URI_PREFIX} or ${UKYC_URI_PREFIX}`,);",
      },
    ],
  });

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: "contentSizeSchema",
        initializer: `z.number().int().positive()`,
      },
    ],
  });

  // yyyy-mm-ddThh:mm:ssZ, the format parse_unix_timestamp and idos.parse_date require.
  // precision 0 rejects fractional seconds; offsets and timezone-less values stay invalid.
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: "rfc3339DateTimeSchema",
        initializer: `z.iso.datetime({ precision: 0 })`,
      },
    ],
  });

  sourceFile.addTypeAlias({
    isExported: true,
    name: "ActionSchemaElement",
    type: `{
      name: string;
      type: typeof DataType.Uuid | typeof DataType.Text | typeof DataType.Int | typeof DataType.Boolean;
    }`,
  })

  const schemaDbMapping = {
    TEXT: "DataType.Text",
    UUID: "DataType.Uuid",
    INT: "DataType.Int",
    BOOLEAN: "DataType.Boolean",
    BOOL: "DataType.Boolean",
    INT8: "DataType.Int",
    NUMERIC: "DataType.Int",
  }

  // Generate action schema
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "actionSchema",
        type: "Record<string, ActionSchemaElement[]>",
        initializer: writer => {
          writer.inlineBlock(() => {
            methods.forEach(method => {
              writer.writeLine(`${method.name}: [`);
              method.args.forEach(arg => {
                writer.inlineBlock(() => {
                  writer.writeLine(`name: "${arg.name}",`);
                  writer.writeLine(`type: ${schemaDbMapping[arg.type]},`);
                });
                writer.write(",");
                writer.newLineIfLastNot();
              });
              writer.writeLine("],");
            })
          });
        }
      },
    ],
  });

  const zodDbMapping = {
    TEXT: "string",
    UUID: "uuid",
    INT: "number",
    BOOLEAN: "boolean",
    BOOL: "boolean",
    INT8: "number",
    NUMERIC: "number",
  }

  const customZodDbMapping: Record<string, string> = {
    wallet_type: "walletTypeSchema",
    encryption_password_store: "encryptionPasswordStoreSchema",
  }

  const zodTypeMapping = {
    TEXT: "ZodString",
    UUID: "ZodUUID",
    INT: "ZodNumber",
    BOOLEAN: "ZodBoolean",
    BOOL: "ZodBoolean",
    INT8: "ZodNumber",
    NUMERIC: "ZodNumber",
  }

  const customZodTypeMapping: Record<string, string> = {
    wallet_type: "z.ZodType<WalletType>",
    encryption_password_store: "z.ZodType<EncryptionPasswordStore>",
  }

  function isContentUriField(name: string): boolean {
    return name === "content_uri" || name.endsWith("_content_uri");
  }

  function isContentSizeField(name: string): boolean {
    return name === "content_size" || name.endsWith("_content_size");
  }

  // Exact names, or the same names with a dwg_ prefix. audit_not_after does not match.
  const RFC3339_FIELD = /^(?:dwg_)?(?:not_usable_before|not_usable_after|not_before|not_after|access_grant_timelock)$/;

  function isRfc3339DateTimeField(arg: Value): boolean {
    return arg.type === "TEXT" && RFC3339_FIELD.test(arg.name);
  }

  const ADD_WALLET_ACTIONS = new Set(["add_wallet", "add_wallet_message"]);

  function zodSchemaForArg(arg: Value, refineBlobFields: boolean, methodName: string): string {
    if (arg.name === "wallet_type" && ADD_WALLET_ACTIONS.has(methodName)) {
      return "addWalletTypeSchema";
    }
    if (customZodDbMapping[arg.name]) {
      return customZodDbMapping[arg.name];
    }
    // Only refine write-path (input) blob fields. Reads can return null content/content_uri/content_size.
    if (refineBlobFields) {
      if (isContentUriField(arg.name)) {
        return "blobContentUriSchema";
      }
      if (isContentSizeField(arg.name)) {
        return "contentSizeSchema";
      }
    }
    if (isRfc3339DateTimeField(arg)) {
      return "rfc3339DateTimeSchema";
    }
    return `z.${zodDbMapping[arg.type]}()`;
  }

  function zodTypeForArg(arg: Value, methodName: string): string {
    if (arg.name === "wallet_type" && ADD_WALLET_ACTIONS.has(methodName)) {
      return "z.ZodType<AddWalletType>";
    }
    if (customZodTypeMapping[arg.name]) {
      return customZodTypeMapping[arg.name];
    }
    if (isRfc3339DateTimeField(arg)) {
      return "z.ZodISODateTime";
    }
    return `z.${zodTypeMapping[arg.type]}`;
  }

  function generateZodType(name: string, args: Value[], {
    optionals = [],
    refineBlobFields = false,
    nullWhen = [],
    nullish = false,
    methodName,
  }: {
    optionals?: string[],
    refineBlobFields?: boolean,
    nullWhen?: GeneratorComments["paramNullWhen"],
    // Inputs: optionals may be omitted, the client sends missing keys as null.
    nullish?: boolean,
    methodName: string,
  }): string | undefined {
    if (args.length === 0) return;

    sourceFile.addVariableStatement({
      declarationKind: VariableDeclarationKind.Const,
      isExported: true,
      declarations: [
        {
          name: `${name}Schema`,
          type: writer => {
            writer.write(`z.ZodObject < `);
            writer.inlineBlock(() => {
              args.forEach(arg => {
                writer.write(`${arg.name}: `);
                if (optionals.includes(arg.name)) {
                  writer.write(nullish ? "z.ZodOptional<z.ZodNullable<" : "z.ZodNullable<");
                }

                writer.write(`${zodTypeForArg(arg, methodName)} `);

                if (optionals.includes(arg.name)) {
                  writer.write(nullish ? ">>" : ">");
                }

                writer.write(";");
                writer.newLine();
              });
            });
            writer.write(">");
          },
          initializer: writer => {
            writer.write(`z.object(`);
            writer.inlineBlock(() => {
              args.forEach(arg => {
                const type = zodSchemaForArg(arg, refineBlobFields, methodName);

                writer.write(`${arg.name}: ${type}`);
                writer.conditionalWrite(optionals.includes(arg.name), () => nullish ? ".nullish()" : ".nullable()");
                writer.write(",");
                writer.newLine();
              });
            });
            writer.write(")");
            nullWhen.forEach(({ field, value, params }) => {
              params.forEach(param => {
                writer.write(`.refine(v => (v.${field} === "${value}") === (v.${param} == null), `);
                writer.write(`{ path: ["${param}"], message: "${param} must be null when ${field} is ${value}, and set otherwise" })`);
              });
            });
          },
        },
      ],
    });

    // For others just export the type
    sourceFile.addTypeAlias({
      isExported: true,
      name: name,
      type: `z.infer < typeof ${name}Schema > `,
    });

    return name;
  }

  methods.forEach(method => {
    const name = toCamelCase(method.name);
    const prefix = name[0].toUpperCase() + name.slice(1);

    // Zod schema for inputs
    let inputName: string | undefined = undefined;
    if (method.args.length > 0) {
      inputName = generateZodType(
        `${prefix}Input`,
        method.args,
        {
          optionals: method.generatorComments.paramOptional,
          refineBlobFields: true,
          nullish: true,
          nullWhen: method.generatorComments.paramNullWhen,
          methodName: method.name,
        },
      );
    }

    let outputName: string | undefined = "void";
    if (method.returns.length > 0) {
      outputName = generateZodType(
        `${prefix}Output`,
        method.returns,
        {
          optionals: method.generatorComments.returnOptional,
          methodName: method.name,
        },
      );
    }

    const optionalSingleRow = method.returns.length > 0
      && !method.returnsArray
      && !method.generatorComments.returnRequired;
    const functionDeclaration = sourceFile.addFunction({
      name,
      isExported: true,
      isAsync: true,
      returnType: `Promise < ${outputName}${method.returnsArray ? "[]" : optionalSingleRow ? " | undefined" : ""} > `,
      parameters: [
        {
          name: "kwilClient",
          type: "KwilActionClient",
        },
        ...(inputName ? [{
          name: "params",
          type: inputName,
        }] : []),
      ],
    });

    if (method.comments.length > 0) {
      functionDeclaration.addJsDoc(method.comments.join("\n"));
    }

    functionDeclaration.setBodyText(writer => {
      let hasReturn = method.returns.length > 0;
      let returnStatement = hasReturn ? "return" : "";
      let methodCall = hasReturn ? `call < ${outputName}[] > ` : "execute";
      // Call always returns an array, if it is one item (not a RETURN TABLE) we need to get the first element
      const firstRow = method.generatorComments.returnRequired
        ? `.then(result => { if (!result[0]) throw new Error("${method.name} returned no rows"); return result[0]; })`
        : `.then(result => result[0])`;

      if (method.args.length > 0) {
        writer.writeLine(`const inputs = ${inputName}Schema.parse(params); `);
        writer.writeLine(`${returnStatement} await kwilClient.${methodCall} (`)
        writer.block(() => {
          writer.writeLine(`name: "${method.name}", `);
          writer.writeLine(`inputs, `);
          writer.conditionalWrite(!!method.generatorComments.description && !hasReturn, () => `description: "${method.generatorComments.description}", `);
        });
        writer.conditionalWriteLine(method.generatorComments.notAuthorized, () => `, undefined, // Signer is not required here`);
        writer.write(")");
        writer.conditionalWrite(hasReturn && !method.returnsArray, () => firstRow);
        writer.write(";");
      } else {
        writer.write(`${returnStatement} await kwilClient.${methodCall}(`);
        writer.block(() => {
          writer.write(`name: "${method.name}",`);
          writer.write(`inputs: {},`);
          writer.conditionalWrite(!!method.generatorComments.description, () => `description: "${method.generatorComments.description}", `);
        });
        writer.write(")");
        writer.conditionalWrite(hasReturn && !method.returnsArray, () => firstRow);
        writer.write(";");
      }
    })
  });

  sourceFile.formatText({
    placeOpenBraceOnNewLineForControlBlocks: true,
  })
  sourceFile.saveSync();
}
