version: "0.2"
dictionaries:
  - english
  - sql
  - project-words
  - ethereum
dictionaryDefinitions:
  - name: project-words
    path: ./project-words.txt
    addWords: true
ignorePaths:
  - generator/node_modules/**
  - generator/src/parser/*.ne
  - generator/src/parser/sql-action.cjs
  - generator/src/parser/lexer.cjs
