name: CI
on: [push]

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: '**/.github/workflows/ci.yml'

      - run: npx cspell --no-progress '**'
